version: "3"

services:
  reverse-proxy:
    # The official v2.0 Traefik docker image
    image: traefik:alpine
    # Enables the web UI and tells Traefik to listen to docker
    command: --api --docker
    ports:
      - "80:80" # The HTTP port
      - "8080:8080" # The Web UI (enabled by --api)
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
      - ./acme.json:/acme.json
    command:
      - --debug=false
      - --logLevel=ERROR
      - --defaultentrypoints=https,http
      - --entryPoints=Name:http Address::80 Redirect.EntryPoint:https
      - --entryPoints=Name:https Address::443 TLS
      - --retry
      - --docker.endpoint=unix:///var/run/docker.sock
      - --docker.domain=bubblebees.tk
      - --docker.watch=true
      - --docker.exposedbydefault=false
      - --acme.email=arcanine1450222@gmail.com
      - --acme.storage=acme.json
      - --acme.entryPoint=https
      - --acme.onHostRule=true
      - --acme.httpchallenge.entrypoint=http
  web1:
    build: ./web
    environment:
      - name=blog1
    labels:
      - traefik.frontend.rule=PathPrefixStrip:/blog1
      - traefik.port=5000
    ports:
      - 5001:5000

  web2:
    build: ./web
    environment:
      - name=blog2
    labels:
      - traefik.frontend.rule=PathPrefixStrip:/blog2
      - traefik.port=5000
    ports:
      - 5002:5000
      
  soceart:
    build: ./soceart
    container_name: soceart
    labels:
      - traefik.frontend.rule=PathPrefixStrip:/soceart
      - traefik.basic.frontend.rule=Host:bubblebees.tk
      - traefik.port=80
    ports:
      - 5003:80
    restart: always